version: '3.4'

services:
  db:
    image: postgres:12.9-alpine
    networks:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker/db/.env
    ports:
      - 5432:5432

  redis:
    image: redis
    networks:
      - redis
    volumes:
      - redis:/data

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    networks:
      backend:
      redis:
      db:
    volumes:
      - ./:/app
      - ~/.bash_history:/root/.bash_history
      - ${SHARED_FOLDER_PATH:-/Users/shared_folder}:/app/shared
    command: |
      /usr/bin/env sh -c "wait-for db:5432 --
      alembic revision --autogenerate
      alembic upgrade head
      python3 main.py"
    env_file:
      - docker/app/.env
      - docker/db/.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - IPYTHONDIR=/app/.ipython
    container_name: third_world_app

networks:
  db:
    driver: bridge
  backend:
    driver: bridge
  redis:
    driver: bridge

volumes:
  redis:
    name: third_world_redis
    driver: local
  pgdata:
    name: third_world_db
    driver: local
